version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0
    container_name: elasticsearch
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - esdata:/usr/share/elasticsearch/data
      - esdata:/usr/share/elasticsearch/logs
    logging:
      driver: "json-file"
      options:
        max-file: "20"
        max-size: "50"
    ports:
      - 9200:9200
    networks:
      - backend

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
      - esdata:/usr/share/elasticsearch/data
      - esdata:/usr/share/elasticsearch/logs
    container_name: kibana
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    logging:
      driver: "json-file"
      options:
        max-file: "20"
        max-size: "50"
    ports:
      - 5601:5601
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  esdata:
    driver: local
