version: '3'
services:
#WORK IN PROGRESS
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.2
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      bootstrap.memory_lock: "false"
      cluster.name: "docker-cluster"
      http.port: 9200
      transport.tcp.port: 9300
      network.host: 0.0.0.0
      node.data: "true"
      node.master: "true"
      node.name: "node_1"
      node.max_local_storage_nodes: 2
      discovery.zen.minimum_master_nodes: 1
      discovery.zen.ping.unicast.hosts: "127.0.0.1:9300"
#      xpack.security.enabled: "false"
    logging:
      driver: "json-file"
      options:
        max-file: "20"
        max-size: "50"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - esdata:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
    networks:
      - backend

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.6.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    logging:
      driver: "json-file"
      options:
        max-file: "20"
        max-size: "50"
    volumes:
      - esdata:/usr/share/elasticsearch/data
      - esdata:/usr/share/elasticsearch/logs
    ports:
      - 5601:5601
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  esdata:
    driver: local
